### PR TITLE
Fix dependencies for npm

### PR DESCRIPTION
**Pull request by kapetan**
At the moment it's not possible to require `kurento-utils` with `browserify` after installing thorugh npm. The `uuid` module needs to be part of the production dependencies. Same for `browserify-optional`, which needs to be specified in the `browserify` field in the package.json.

### CODE REVIEW

**Comment by vhmth** [comment]
Running into this as well. Output of webpack:

```
ERROR in ./~/kurento-utils/lib/WebRtcPeer.js
Module not found: Error: Cannot resolve module 'uuid' in /Users/vinay/Code/Engage/node_modules/kurento-utils/lib
 @ ./~/kurento-utils/lib/WebRtcPeer.js 18:11-26
```

**Comment by snobear** [comment]
I am also hitting this.

```
Module not found: Error: Cannot resolve module 'uuid'
Module not found: Error: Cannot resolve module 'sdp-translator'
```

npm installing them resolved it for me.

**Comment by riggs** [comment]
uuid and sdp-translator are still missing as dependancies.

**Comment by igracia** [comment]
It should be fixed in [this](https://github.com/Kurento/kurento-utils-js/commit/82788d947ff4197e496930523d41bb5a87a0e443) commit.

**Pull request closed without merging**
